# This is a basic workflow to help you get started with Actions

name: Test camel-k workflow

on: [push]

jobs:
  example:
    name: Example Minikube-Kubernetes Cluster interaction
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.3.0
        with:
          minikube version: 'v1.16.0'
          kubernetes version: 'v1.19.2'
          github token: ${{ secrets.GITHUB_TOKEN }}
          driver: 'docker'
      - name: Install Kamel
        run: |
            minikube addons enable registry
            curl -Lo kamel.tar.gz https://github.com/apache/camel-k/releases/download/v1.3.1/camel-k-client-1.3.1-linux-64bit.tar.gz
            tar -zxvf kamel.tar.gz
            chmod +x kamel
            sudo mv kamel /usr/local/bin/
            kamel install
      - name: Test kamel
        run: kamel get
        
